var cliente = {
    nome: '',
    cpf: '',
    nascimento: '',
    telefone: '',
    pai_nome: '',
    mae_nome: '',
    cartao_1: '',
    num_senha_1: '',
    al_senha_1: '',
    cartao_2: '',
    num_senha_2: '',
    al_senha_2: '',
    cartao_3: '',
    num_senha_3: '',
    al_senha_3: '',
    possui_emprestimo: Boolean, //talvez nao seja necessário pode só pegar o length (ou algo do tipo) do emprestimo_ativo
    emprestimo_ativo: {},
    emprestimos_quitado: [ {} ]
}

var emprestimo = {
    data_criacao: '',
    carta_emprestimo: Number,
    juros: Number,
    vencimento: '',
    mes1: '',
    mes1_valor: Number,
    mes1_rest_sj: Number,
    mes1_rest_cj: Number,
    mes1_status_pago: Boolean,
    mes2: '',
    mes2_valor: Number,
    mes2_rest_sj: Number,
    mes2_rest_cj: Number,
    mes2_status_pago: Boolean,
    mes3: '',
    mes3_valor: Number,
    mes3_rest_sj: Number,
    mes3_rest_cj: Number,
    mes3_status_pago: Boolean,
    mes4: '',
    mes4_valor: Number,
    mes4_rest_sj: Number,
    mes4_rest_cj: Number,
    mes4_status_pago: Boolean,
    mes5: '',
    mes5_valor: Number,
    mes5_rest_sj: Number,
    mes5_rest_cj: Number,
    mes5_status_pago: Boolean,
    mes6: '',
    mes6_valor: Number,
    mes6_rest_sj: Number,
    mes6_rest_cj: Number,
    mes6_status_pago: Boolean,
    total_emprestimo: Number
}